# Generated by Django 5.0.2 on 2025-11-28 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0005_alter_maestros_options_remove_maestros_clave_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_objetivo', models.CharField(max_length=255)),
                ('programa_educativo', models.CharField(blank=True, choices=[('Ingeniería en Ciencias de la Computación', 'Ingeniería en Ciencias de la Computación'), ('Licenciatura en Ciencias de la Computación', 'Licenciatura en Ciencias de la Computación'), ('Ingeniería en Tecnologías de la Información', 'Ingeniería en Tecnologías de la Información')], max_length=100, null=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('cupo', models.PositiveIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
